# Generated by Django 5.0.6 on 2025-03-06 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('penandatangan', models.CharField(max_length=255)),
                ('tanggal_ditandatangani', models.DateField()),
                ('lembaga_mengeluarkan', models.CharField(max_length=255)),
                ('no_dokumen', models.CharField(max_length=100, unique=True)),
                ('status_dokumen', models.CharField(max_length=50)),
                ('lokasi_penerbit', models.CharField(max_length=255)),
                ('sumber', models.TextField()),
                ('ringkasan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Komponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_komponen', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeterkaitanDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_total_keterkaitan', models.FloatField()),
                ('dok_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keterkaitan_dok_1', to='documents.dokumen')),
                ('dok_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keterkaitan_dok_2', to='documents.dokumen')),
            ],
        ),
        migrations.CreateModel(
            name='KeterkaitanKomponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_keterkaitan_komponen', models.FloatField()),
                ('keterkaitan_dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.keterkaitandokumen')),
                ('komponen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.komponen')),
            ],
        ),
        migrations.CreateModel(
            name='DokumenKomponen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_komponen', models.TextField()),
                ('dokumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.dokumen')),
                ('komponen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.komponen')),
            ],
        ),
    ]
