# Generated by Django 5.0.6 on 2025-03-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_dokumen_komponen_keterkaitandokumen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='tanggal_ditandatangani',
            field=models.CharField(max_length=255),
        ),
    ]
