# Generated by Django 5.0.6 on 2025-03-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_dokumen_tanggal_ditandatangani'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumen',
            name='no_dokumen',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='komponen',
            name='nama_komponen',
            field=models.CharField(max_length=255),
        ),
    ]
